spring:
  application:
    name: kitchen-sink-migration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017}/members
      auto-index-creation: true

server:
  port: 8080

