version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"
